version: "3.7"

services:
  parallel-airdrop:
    container_name: parallel-airdrop
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "$GRAPHQL_PORT:$GRAPHQL_PORT"
    env_file: .env
    restart: always
